# setting up my first worflow
name: my first workflow
on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  myFirstJob:
    name: My first job
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello ${{vars.WHO_TO_GREET}} from ${{github.actor}}"
          echo "My secret is ${{secrets.MY_SECRET}}"
          echo "The current branch is ${{github.ref}}"
        
      - name: checkout
        uses: actions/checkout@v4.1.0
      - run: tree
      
     
  Test:
    runs-on: ubuntu-latest
    environment: Test
    needs: myFirstJob
    steps:
    - run: |
        echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "My secret is 🤫 '$sec'."
      
  Load-Test:
    runs-on: ubuntu-latest
    environment: Load-Test
    needs: myFirstJob
    steps:
    - run: |
        echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "My secret is 🤫 '$sec'."
        sleep 15
      
  Production:
    runs-on: ubuntu-latest
    environment: 
      name: Production
      url: https://writeabout.net
    needs: [Test, Load-Test]
    steps:
    - run: |
        echo "Hello ${{ vars.WHO_TO_GREET }} 👋 from ${{ github.actor }}." 
        sec=$(echo ${{ secrets.MY_SECRET }} | sed 's/./& /g')
        echo "My secret is 🤫 '$sec'."
        sleep 15  
